# Polynomial Regression

## Importing the libraries

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [5]:
dataset = pd.read_csv('datasets/Position_Salaries.csv')
X = dataset.iloc[:, 1: -1].values
y = dataset.iloc[:, -1].values

## Training the Linear Regression model on the whole dataset

In [7]:
from sklearn.linear_model import LinearRegression
lin_regressor = LinearRegression()
lin_regressor.fit(X, y)

LinearRegression()

## Training the Polynomial Regression model on the whole dataset

In [8]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X)
poly_regressor = LinearRegression()
poly_regressor.fit(X_poly, y)

LinearRegression()

In [9]:
print(X_poly)

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03]
 [1.000e+00 7.000e+00 4.900e+01 3.430e+02 2.401e+03]
 [1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
 [1.000e+00 9.000e+00 8.100e+01 7.290e+02 6.561e+03]
 [1.000e+00 1.000e+01 1.000e+02 1.000e+03 1.000e+04]]


## Visualising the Linear Regression results

In [10]:
plt.scatter(X, y ,color = 'red')
plt.plot(X, lin_regressor.predict(X))
plt.title("Linear regression")
plt.xlabel("Position level")
plt.ylabel("Salary")
plt.show()

## Visualising the Polynomial Regression results

In [11]:
plt.scatter(X, y ,color = 'red')
plt.plot(X, poly_regressor.predict(X_poly))  #Incresing degree improved the  curve fitting the line , infact overfit now
plt.title("Polynomial regression")
plt.xlabel("Position level")
plt.ylabel("Salary")
plt.show()

## Visualising the Polynomial Regression results (for higher resolution and smoother curve)

## Predicting a new result with Linear Regression

In [12]:
print(lin_regressor.predict([[6.5]]))

[330378.78787879]


## Predicting a new result with Polynomial Regression

In [13]:
print(poly_regressor.predict(poly_reg.fit_transform([[6.5]]))) #the fit_transform method fits and transforms 6.5 depending on the degree of poly considered
                            #above equation does the same operation as the statement below
print(poly_regressor.predict(([[1 ,6.5 ,6.5**2,6.5**3,6.5**4]])))

[158862.4526515]
[158862.4526515]
